<script>
  export let src = './backgrounds/0.png';
  const srcFileName = src.split('/').pop();
  export let alt = `Background generated by AI. (${srcFileName})`;
</script>

<div class="hidden lg:block min-h-screen max-h-screen">
  <img {src} {alt} class="object-cover min-h-screen w-100%" />
</div>
